services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: phyto
      POSTGRES_PASSWORD: phyto_dev_pass
      POSTGRES_DB: phyto_ecommerce
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
